version: 2.1
executors:
  node18:
    docker:
      - image: cimg/node:18.2

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install npm
          command: sudo npm -g install npm
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node18
    steps:
      - setup
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
